version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "azdo-task/DevcontainersCi"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/github-action"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/.github/scripts"
    schedule:
      interval: "weekly"
