name: 'Dev Container Build and Run Action'
description: 'Action to simplify using Dev Containers (https://containers.dev) in GitHub workflows'
author: 'devcontainers'
branding:
  color: purple
  icon: box
inputs:
  imageName:
    required: false
    description: Image name (including registry)
  imageTag:
    required: false
    description: Image tag (defaults to latest)
  runCmd:
    required: false
    description: Specify the command to run after building the dev container image. Can be omitted to skip starting the container.
  subFolder:
    required: false
    description: Specify a child folder (containing a .devcontainer) instead of using the repository root
    default: 
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
  push:
    required: false
    default: filter
    description: Control when images are pushed. Options are never, filter, always. For filter (default), images are pushed if the refFilterForPush and eventFilterForPush conditions are met
  refFilterForPush:
    required: false
    default:
    description: Set the source branches (e.g. refs/heads/main) that are allowed to trigger a push of the dev container image. Leave empty to allow all.
  eventFilterForPush:
    required: false
    default: push
    description: Set the event names (e.g. pull_request, push) that are allowed to trigger a push of the dev container image. Defaults to push. Leave empty for all
  env:
    required: false
    description: Specify environment variables to pass to the docker run command
  skipContainerUserIdUpdate:
    required: false
    default: false
    description: For non-root Dev Containers (i.e. where `remoteUser` is specified), the action attempts to make the container user UID and GID match those of the host user. Set this to true to skip this step (defaults to false)
  userDataFolder:
    required: false
    description: Some steps for building the dev container (e.g. container-features) require generating additional build files. To aid docker build cache re-use, you can use this property to set the path that these files will be generated under and use the actions/cache action to cache that folder across runs
  cacheFrom:
    required: False
    description: Specify additional images to use for build caching
outputs:
  runCmdOutput:
    description: The output of the command specified in the runCmd input
runs:
  using: 'node16'
  main: 'github-action/run-main.js'
  post: 'github-action/run-post.js'
  post-if: 'success()'
