---
name: CI (main)
# This workflow is triggered on pushes to main and runs tests and performs the release steps

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      publishAzdoExtension:
        description: Publish the AzDO extension
        type: boolean
        default: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  checks: write

jobs:
  build-test-publish:
    name: "Build, test, publish"
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ci_common.yml
    with:
      release: true
      publishAzdoExtension: ${{ inputs.publishAzdoExtension == '' && true || inputs.publishAzdoExtension }}
    secrets:
      AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
