name: pr_closed

on:
  pull_request:
    types: [closed]

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request

jobs:

  pr_closed:
    name: PR Closed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Clean GitHub container images for PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_IMAGE_TAG: pr-${{ github.event.pull_request.number }}
        run:
          ./.github/workflows/clean_tags.sh --tag $PR_IMAGE_TAG
